### ISSUE TITLE
Only because I want to torment you 😈😈😈

### ISSUE THREAD

**Issue by ItsSchatten** [adard2002/Anime-Project.html#1]
I mean, I am the person that you go to when you need help with a coding question. So I'm raising an issue just for you to resolve!

It's fun being a programmer aint it? Also, for the love of god, PLEASE keep your folder naming consistent, I mean JS, CSS and then animeimages and merchimages.

**Comment by adard2002** [comment]
Yis, thank you for le helppp

**Comment by ItsSchatten** [comment]
Nein.

**Comment by adard2002** [comment]
Nani?
